# Generated by Django 5.0.4 on 2025-06-03 08:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("body", models.TextField()),
                ("tagList", models.JSONField(blank=True, default=list)),
                ("createdAt", models.DateTimeField(default=django.utils.timezone.now)),
                ("updatedAt", models.DateTimeField(default=django.utils.timezone.now)),
                ("favorited", models.BooleanField(default=False)),
                ("favoritesCount", models.IntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="api.user",
                    ),
                ),
            ],
        ),
    ]
